# Use Ubuntu 14.04 on Travis.
sudo: required
dist: trusty

os:
  - linux
  - osx

matrix:
  allow_failures:
    - env: JULIA_PPA=julianightlies

env:
  - JULIA_PPA=juliareleases
  - JULIA_PPA=julianightlies

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sudo add-apt-repository ppa:staticfloat/$JULIA_PPA -y
    && sudo apt-get update -q
    && sudo apt-get install julia -y; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update
    && brew tap staticfloat/julia
    && if [ "$JULIA_PPA" = "julianightlies" ]; then
    brew install --HEAD julia;
    else brew install julia; fi;
    fi

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CompilerTools"); Pkg.test("CompilerTools")'

