# Use Ubuntu 14.04 on Travis.
sudo: required
dist: trusty

os:
  - linux
  - osx

# Because there's no Julia by default on the Travis Trusty beta, we have to install it.
before_install:
  - sudo add-apt-repository ppa:staticfloat/juliareleases -y
  - sudo apt-get update -q
  - sudo apt-get install julia -y

script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("CompilerTools"); Pkg.test("CompilerTools")'
