# Use Ubuntu 14.04 on Travis.
sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - test $TRAVIS_OS_NAME = "linux"
    && sudo add-apt-repository ppa:staticfloat/juliareleases -y
    && sudo apt-get update -q
    && sudo apt-get install julia -y
  - test $TRAVIS_OS_NAME = "osx"
    && brew update
    && brew tap staticfloat/julia
    && brew install julia

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CompilerTools"); Pkg.test("CompilerTools")'
