language: julia

# Use Ubuntu 14.04 on Travis.
sudo: required
dist: trusty

os:
  - linux
  - osx

julia:
  - 0.4.0
  - 0.4.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("CompilerTools"); Pkg.test("CompilerTools")'

